name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - 1.78.0 # MSRV
        include:
          - os: ubuntu-latest
            rust: 1.78.0
            lint: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v1

      - name: cargo check
        run: cargo check

      - name: cargo build
        run: cargo build

      - name: cargo test
        run: cargo test

      - name: rustfmt
        if: github.event_name == 'pull_request' && matrix.lint
        run: cargo fmt --all -- --check

      - name: clippy
        if: github.event_name == 'pull_request' && matrix.lint
        run: cargo clippy --all --tests -- -D warnings
